Web/Models/SupplierViewModel.cs
namespace Web.Models
{
    public class SupplierViewModel
    {
        public int Id { get; set; }
        //public string IsVip { get; set; }
        public string Name { get; set; }
       // public string LastName { get; set; }
    }
}

Web/Controllers/CustomerController.cs
using DatabaseContext.Models;
using DatabaseContext.UnitOfWork;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Web.Models;

namespace Web.Controllers
{
    public class CustomerController : BaseController
    {
        public CustomerController(IUnitOfWork unitOfWork)
           : base(unitOfWork)
        {

        }

        public IActionResult Index(int pg = 1)
        {
            var customers = _unitOfWork.CustomerRepo.GetAll();
            var sortedCustomers = customers.OrderByDescending(x => x.Id).ToList();

            const int pageSize = 4;
            if (pg < 1)
                pg = 1;

            int resCount = sortedCustomers.Count();
            var pager = new Pager(resCount, pg, pageSize);
            int recSkip = (pg - 1) * pageSize;
            var data = sortedCustomers.Skip(recSkip).Take(pager.PageSize).ToList();
            this.ViewBag.Pager = pager;
             return View(data);

            //return View(customers);
        }

        public IActionResult GetCustomers()
        {
            var deps = _unitOfWork.CustomerRepo.GetAll();
            return Json(new
            {
                success = true,
                message = "All Data is back",
                data = deps
            });
        }

        public IActionResult Create()
        {
            return View();
        }

        // GET: Employees/Edit/5
        public IActionResult Edit(int id)
        {
           
                var customer = _unitOfWork.CustomerRepo.Get(id);
                if (customer == null)
                {
                    return NotFound();
                }
                return View(customer);
           
        }

        // POST: Employees/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("Id,FirstName,LastName,IsVip")] Customer customer)
        {
            if (id != customer.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
              
                    _unitOfWork.CustomerRepo.Update(customer);
                    _unitOfWork.save();
                
                
                return RedirectToAction(nameof(Index));
            }
            return View(customer);
        }


        [HttpPost]
        public IActionResult Create(DatabaseContext.Models.Customer
            customer)
        {

            if (ModelState.IsValid)
            {
                _unitOfWork.CustomerRepo.Add(customer);
                _unitOfWork.save();
                TempData["SweetAlert"] = "suc";
                return RedirectToAction("Index");
            }
            else
            {
                TempData["SweetAlert"] = "oop";
                return View();
            }
        }


        public  IActionResult Delete(int id)
        {

            var customer = _unitOfWork.CustomerRepo.GetAll().FirstOrDefault(m => m.Id == id);
            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }

        // POST: Employees/Delete/5
        // [HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        [HttpPost, ActionName("Delete")]
        public  IActionResult DeleteConfirmed(int id)
        {
            var customer =  _unitOfWork.CustomerRepo.Get(id);
            _unitOfWork.CustomerRepo.Delete(customer);
            _unitOfWork.save();
            return RedirectToAction(nameof(Index));
        }


        public IActionResult Search(string value)
        {
            var deps = string.IsNullOrEmpty(value) ? _unitOfWork.CustomerRepo.GetAll()
                : _unitOfWork.CustomerRepo.GetAll()
                .Where(e => e.FirstName.ToLower().Contains(value.ToLower()) || e.LastName.ToLower().Contains(value.ToLower()));
            return Json(new
            {
                success = true,
                message = "All Data is back",
                data = deps
            });
        }


        [HttpGet]
        public IActionResult GetCustomer(int customerId)
        {
            var customer = _unitOfWork.CustomerRepo.Get(customerId);

            if (customer == null)
            {
                return NotFound();
            }

            return Json(new
            {
                f_name = customer.FirstName,
                l_name = customer.LastName,
                is_vip = customer.IsVip
            });
        }
        
        [HttpGet]
        public IActionResult GetAllCustomers()
        {
            var customers = _unitOfWork.CustomerRepo.GetAll();

            if (customers == null)
            {
                return NotFound();
            }

            var customerList = new List<Object>();
            foreach (var customer in customers)
            {
                customerList.Add(new
                {
                    f_name = customer.FirstName,
                    l_name = customer.LastName,
                    is_vip = customer.IsVip
                });
            }

            return Json(customerList);
        }
    }

}

Web/Controllers/SupplierController.cs
using DatabaseContext.Models;
using DatabaseContext.UnitOfWork;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Threading.Tasks;
using Web.Models;

namespace Web.Controllers
{
    public class SupplierController : BaseController
    {
        public SupplierController(IUnitOfWork unitOfWork)
           : base(unitOfWork)
        {

        }

        public IActionResult Index()
        {
            var suppls = _unitOfWork.SupplierRepo.GetAll();
            ViewBag.Message = "Hello From ViewBag";
            return View(suppls);
        }

        public IActionResult GetCustomers()
        {
            var suppls = _unitOfWork.SupplierRepo.GetAll();
            return Json(new
            {
                success = true,
                message = "All Data is back",
                data = suppls
            });
        }

        public IActionResult Create()
        {
            return View();
        }

        // GET: Employees/Edit/5
        public IActionResult Edit(int id)
        {
           
                var supplier = _unitOfWork.SupplierRepo.Get(id);
                if (supplier == null)
                {
                    return NotFound();
                }
                return View(supplier);
           
        }

        // POST: Employees/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("Id,Name")] Supplier supplier)
        {
            if (id != supplier.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
              
                    _unitOfWork.SupplierRepo.Update(supplier);
                    _unitOfWork.save();
                
                
                return RedirectToAction(nameof(Index));
            }
            return View(supplier);
        }


        [HttpPost]
        public IActionResult Create(DatabaseContext.Models.Supplier
            supplier)
        {

            if (ModelState.IsValid)
            {

                // ViewBag.Message = "Name must be required";
                _unitOfWork.SupplierRepo.Add(supplier);
                _unitOfWork.save();
                TempData["SweetAlertSup"] = "suc";
                return RedirectToAction("Index");
            }
            else
            {
                TempData["SweetAlertSup"] = "suc";
                return View();
            }
        }


        public  IActionResult Delete(int id)
        {

            var supplier = _unitOfWork.SupplierRepo.GetAll().FirstOrDefault(m => m.Id == id);
            if (supplier == null)
            {
                return NotFound();
            }

            return View(supplier);
        }

        // POST: Employees/Delete/5
        // [HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        [HttpPost, ActionName("Delete")]
        public  IActionResult DeleteConfirmed(int id)
        {
            var supplier =  _unitOfWork.SupplierRepo.Get(id);
            _unitOfWork.SupplierRepo.Delete(supplier);
            _unitOfWork.save();
            return RedirectToAction(nameof(Index));
        }


        public IActionResult Search(string value)
        {
            var suppls = string.IsNullOrEmpty(value) ? _unitOfWork.SupplierRepo.GetAll()
                : _unitOfWork.SupplierRepo.GetAll()
                .Where(e => e.Name.ToLower().Contains(value.ToLower()));
            return Json(new
            {
                success = true,
                message = "All Data is back",
                data = suppls
            });
        }


        public IActionResult GetModal(int id)
        {
            return PartialView("_Modal",
                _unitOfWork.SupplierRepo.Get(id)
                );
        }
    }
}

Web/Views/Supplier/Create.cshtml
@model DatabaseContext.Models.Supplier
@if(TempData["SweetAlertSup"] != null)
        {

    <div id="swalme2"></div>
    TempData["SweetAlertSup"] = null;
}

<form class="form" method="post" action="@Url.Action("Create","Supplier")">
    <div class="form-group">
        <label asp-for="Name"></label>
        <input autocomplete="off" asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <input class="btn-sub" onclick="success()" type="submit" />
</form>
    
@section scripts{
      <script>
           //var els = document.getElementById("swalme");
           var els2 = document.getElementById("swalme2");
           if (els2!=null){
                    Swal.fire({
                      icon: 'error',
                      title: 'Oops...',
                      text: 'Invalid Information!',
                      showCancelButton: false,
                      showConfirmButton: false,
                      timer:3000
                    })
           }
    </script>
}

Web/Views/Supplier/Delete.cshtml
@model DatabaseContext.Models.Supplier
@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this Supplier ?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
    </dl>
    <br />
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Web/Views/Supplier/Edit.cshtml
@model DatabaseContext.Models.Supplier

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<hr />
<div>
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Save" onclick="savechanges()" class="btn btn-sub" />
            </div>
        </form>
</div>

<div>
        <a class="back" asp-action="Index"> &lt Back to List</a>
</div>
@*
<script>
        function savechanges() {
                    Swal.fire({
                      title: 'Do you want to save the changes?',
                      showDenyButton: true,
                      showCancelButton: true,
                      confirmButtonText: 'Save',
                      denyButtonText: `Don't save`,
                    }).then((result) => {
                      /* Read more about isConfirmed, isDenied below */
                      if (result.isConfirmed) {
                        Swal.fire('Saved!', '', 'success')
                      } else if (result.isDenied) {
                        Swal.fire('Changes are not saved', '', 'info')
                      }
                    })
                }
                
    </script>*@

Web/Views/Supplier/Index.cshtml
@model List<DatabaseContext.Models.Supplier>
@*
@{ 
    ViewData["title"] = "Index";
}*@

@if(TempData["SweetAlertSup"] != null)
        {

    <div id="swalme"></div>
    TempData["SweetAlertSup"] = null;
}

<div id="msg" class="row my-2">
    <p>
        @TempData["Message"]
    </p>
</div>
<div class="row my-3">
    <div class="col-4">
        <a class="btn btn-primary" href="@Url.Action("Create","Supplier")">Create Supplier</a>
    </div>
    <div class="col-4">
        @*<input type="text" class="form-control srch text-success" placeholder="Search..." onkeyup="search(this.value)" />*@
    </div>
</div>
<div id ="btnshow" style = " display : none">
<table class="table table-bordered">
    <thead>
        <tr>
            <th>FirstName</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
             <tr>
                <td>@item.Name</td>
                <td>
                <a asp-action="Edit" asp-route-id="@item.Id" class="btn  btn-warn">Edit</a>
                <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>
</div>
<button class="btn btn-warn" onclick="showButton()">Get Suppliers</button>

<div id="modal-container">

</div>
@section Scripts {
    <script>
        function get() {
            let i = 10;
            let string = `${i}`;
            $.ajax({
                url: '@Url.Action("GetSuppliers", "Supplier")',
                type: 'GET',
                dataType: 'json',
                beforeSend: function() {
                    let timerInterval
                    Swal.fire({
                      title: 'Loading...',
                      //html: 'I will close in <b></b> milliseconds.',
                      timer: 1000,
                      timerProgressBar: true,
                      didOpen: () => {
                        Swal.showLoading()
                        const b = Swal.getHtmlContainer().querySelector('b')
                        timerInterval = setInterval(() => {
                          b.textContent = Swal.getTimerLeft()
                        }, 100)
                      },
                      willClose: () => {
                        clearInterval(timerInterval)
                      }
                    }).then((result) => {
                      if (result.dismiss === Swal.DismissReason.timer) {
                        console.log('I was closed by the timer')
                      }
                    });
                },
                success: function(response) {
                    if (response.success) {
                        $.each(response.data, (index, item) => {
                            $('tbody').append(` <tr>
                                                    <td>${item.id}</td>
                                                    <td>${item.name}</td>
                                                    <td>
                                                        <button class="btn btn-warning" onclick="showModal('${item.id}')">Edit</button>
                                                        <button class="btn btn-danger">Delete</button>
                                                    </td>
                                                </tr>`)
                        })
                    }
                    else {
                        alert(response.message)
                    }
                },
                error: function(msg) {
                    console.error(msg);
                }
            })
        }
    </script>
    <script>
        function search(val) {
            $.ajax({
                url: '@Url.Action("Search", "Supplier")' + '?value=' + val,
                type: 'GET',
                dataType: 'json',
                beforeSend: function() {
                    $('tbody').html('')
                },
                success: function(response) {
                    if (response.success) {
                        $.each(response.data, (index, item) => {
                            $('tbody').append(` <tr>
                                                    <td>${item.id}</td>
                                                    <td>${item.name}</td>
                                                    <td>
                                                        <button class="btn btn-warn" onclick="showModal('${item.id}')">Edit</button>
                                                        <button class="btn btn-danger">Delete</button>
                                                    </td>
                                                </tr>`)
                        })
                    }
                    else {
                        alert(response.message)
                    }
                },
                error: function(msg) {
                    console.error(msg);
                }
            })
        }
    </script>
    <script>
        function showModal(id) {
            alert(id);
            $.ajax({
                url: '@Url.Action("GetModal", "Supplier")' + "?id=" + parseInt(id),
                type: 'GET',
                dataType: 'html',
                success: function(response) {
                    $('#modal-container').html(response); 
                    $('.modal').modal('show');
                    $.validator.unobtrusive.parse('form-id');
                },
                error: function(msg) {
                    console.error(msg);
                }
            })
        }
    </script>
    <script>
    function showButton(){
       var el = document.getElementById("btnshow");
       el.style.display = "table";
        }
    </script>

    <script>
           var els = document.getElementById("swalme");
           //var els2 = document.getElementById("swalme2");
           if (els!=null){
           Swal.fire({
                      icon: 'success',
                      title: 'Saved',
                      showCancelButton: false,
                      showConfirmButton: false,
                      timer:3000
                    })
           }
           //else if(els2 != null){
           // Swal.fire('OOOOOOPS succefully');
           //}
    </script>
}   

Web/Views/Supplier/_Modal.cshtml
@model DatabaseContext.Models.Supplier
<div class="modal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header"></div>
            <form asp-action="Edit" asp-controller="Customer">
                <div class="modal-body">
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name"></span>
                </div>
            <div class="modal-footer">
                <input type="submit" class="btn btn-primary" value="Submit" />
                <button class="btn btn-light" data-dismiss="modal">Cancel</button>
            </div>
            </form>
        </div>
    </div>
</div>