Web/Controllers/CustomerController.cs
using DatabaseContext.Models;
using DatabaseContext.UnitOfWork;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Web.Models;

namespace Web.Controllers
{
    public class CustomerController : BaseController
    {
        public CustomerController(IUnitOfWork unitOfWork)
           : base(unitOfWork)
        {

        }

        public IActionResult Index(int pg = 1)
        {
            var customers = _unitOfWork.CustomerRepo.GetAll();
            var sortedCustomers = customers.OrderByDescending(x => x.Id).ToList();

            const int pageSize = 4;
            if (pg < 1)
                pg = 1;

            int resCount = sortedCustomers.Count();
            var pager = new Pager(resCount, pg, pageSize);
            int recSkip = (pg - 1) * pageSize;
            var data = sortedCustomers.Skip(recSkip).Take(pager.PageSize).ToList();
            this.ViewBag.Pager = pager;
             return View(data);

            //return View(customers);
        }

        public IActionResult GetCustomers()
        {
            var deps = _unitOfWork.CustomerRepo.GetAll();
            return Json(new
            {
                success = true,
                message = "All Data is back",
                data = deps
            });
        }

        public IActionResult Create()
        {
            return View();
        }

        // GET: Employees/Edit/5
        public IActionResult Edit(int id)
        {
           
                var customer = _unitOfWork.CustomerRepo.Get(id);
                if (customer == null)
                {
                    return NotFound();
                }
                return View(customer);
           
        }

        // POST: Employees/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("Id,FirstName,LastName,IsVip")] Customer customer)
        {
            if (id != customer.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
              
                    _unitOfWork.CustomerRepo.Update(customer);
                    _unitOfWork.save();
                
                
                return RedirectToAction(nameof(Index));
            }
            return View(customer);
        }


        [HttpPost]
        public IActionResult Create(DatabaseContext.Models.Customer
            customer)
        {

            if (ModelState.IsValid)
            {
                _unitOfWork.CustomerRepo.Add(customer);
                _unitOfWork.save();
                TempData["SweetAlert"] = "suc";
                return RedirectToAction("Index");
            }
            else
            {
                TempData["SweetAlert"] = "oop";
                return View();
            }
        }


        public  IActionResult Delete(int id)
        {

            var customer = _unitOfWork.CustomerRepo.GetAll().FirstOrDefault(m => m.Id == id);
            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }

        // POST: Employees/Delete/5
        // [HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        [HttpPost, ActionName("Delete")]
        public  IActionResult DeleteConfirmed(int id)
        {
            var customer =  _unitOfWork.CustomerRepo.Get(id);
            _unitOfWork.CustomerRepo.Delete(customer);
            _unitOfWork.save();
            return RedirectToAction(nameof(Index));
        }


        public IActionResult Search(string value)
        {
            var deps = string.IsNullOrEmpty(value) ? _unitOfWork.CustomerRepo.GetAll()
                : _unitOfWork.CustomerRepo.GetAll()
                .Where(e => e.FirstName.ToLower().Contains(value.ToLower()) || e.LastName.ToLower().Contains(value.ToLower()));
            return Json(new
            {
                success = true,
                message = "All Data is back",
                data = deps
            });
        }


        [HttpGet]
        public IActionResult GetCustomer(int customerId)
        {
            var customer = _unitOfWork.CustomerRepo.Get(customerId);

            if (customer == null)
            {
                return NotFound();
            }

            return Json(new
            {
                f_name = customer.FirstName,
                l_name = customer.LastName,
                is_vip = customer.IsVip
            });
        }
        
        [HttpGet]
        public IActionResult GetAllCustomers()
        {
            var customers = _unitOfWork.CustomerRepo.GetAll();

            if (customers == null)
            {
                return NotFound();
            }

            var customerList = new List<Object>();
            foreach (var customer in customers)
            {
                customerList.Add(new
                {
                    f_name = customer.FirstName,
                    l_name = customer.LastName,
                    is_vip = customer.IsVip
                });
            }

            return Json(customerList);
        }
    }

}

Web/Controllers/ProductEntryController.cs
using DatabaseContext.Models;
using DatabaseContext.UnitOfWork;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Web.Models;

namespace Web.Controllers
{
    public class ProductEntryController : BaseController
    {
        public ProductEntryController(IUnitOfWork unitOfWork)
           : base(unitOfWork)
        {

        }

        public IActionResult Index()
        {
            var orders = _unitOfWork.ProductEntryRepo.GetAll();

            foreach (var order in orders)
            {
                order.Supplier = _unitOfWork.SupplierRepo.Get(order.SupplierId);
            }
            ViewBag.Message = "Hello From ViewBag";
            // ViewData["Message"] = "Hello From ViewData";
            return View(orders);
        }

        public IActionResult GetProductEntries()
        {
            var productEntries = _unitOfWork.ProductEntryRepo.GetAll();
            return Json(new
            {
                success = true,
                message = "All Data is back",
                data = productEntries
            });
        }

        public IActionResult Edit(int id)
        {
            List<SelectListItem> list = new List<SelectListItem>();
            var suppliers = _unitOfWork.SupplierRepo.GetAll();
            foreach (var supplier in suppliers)
            {
                list.Add(new SelectListItem
                {
                    Text = supplier.Name,
                    Value = supplier.Id.ToString()
                });
            }
            ViewBag.suppliers = list;
            var pEntry = _unitOfWork.ProductEntryRepo.Get(id);
            if (pEntry == null)
            {
                return NotFound();
            }
            return View(pEntry);

        }

        
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("Id,SupplierId,Date")] ProductEntry pEntry)
        {
            List<SelectListItem> list = new List<SelectListItem>();
            var suppliers = _unitOfWork.SupplierRepo.GetAll();
            foreach (var supplier in suppliers)
            {
                list.Add(new SelectListItem
                {
                    Text = supplier.Name,
                    Value = supplier.Id.ToString()
                });
            }
            ViewBag.suppliers = list;
            if (id != pEntry.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {

                _unitOfWork.ProductEntryRepo.Update(pEntry);
                _unitOfWork.save();


                return RedirectToAction(nameof(Index));
            }
            return View(pEntry);
        }

        public IActionResult Create()
        {
            List<SelectListItem> list = new List<SelectListItem>();
            var suppliers = _unitOfWork.SupplierRepo.GetAll();
            foreach (var supplier in suppliers)
            {
                list.Add(new SelectListItem
                {
                    Text = supplier.Name,
                    Value = supplier.Id.ToString()
                });
            }
            ViewBag.suppliers = list;
            return View();
        }


        [HttpPost]
        public IActionResult Create(DatabaseContext.Models.ProductEntry pEntry)
        {
            List<SelectListItem> list = new List<SelectListItem>();
            var suppliers = _unitOfWork.SupplierRepo.GetAll();
            foreach (var supplier in suppliers)
            {
                list.Add(new SelectListItem
                {
                    Text = supplier.Name,
                    Value = supplier.Id.ToString()
                });
            }
            ViewBag.suppliers = list;

            if (ModelState.IsValid)
            {
                int supID = pEntry.SupplierId;
                pEntry.Supplier = _unitOfWork.SupplierRepo.Get(supID);
                _unitOfWork.ProductEntryRepo.Add(pEntry);
                _unitOfWork.save();
                ViewBag.newname = pEntry.Supplier.Name;
                TempData["SweetAlertPE"] = "suc";
                return RedirectToAction("Index");
            }
            else
            {
                TempData["SweetAlertPE"] = "suc";
                return View();
            }
        }



        public IActionResult Delete(int id)
        {

            var pEntry = _unitOfWork.ProductEntryRepo.GetAll().FirstOrDefault(m => m.Id == id);
            if (pEntry == null)
            {
                return NotFound();
            }

            return View(pEntry);
        }

        // POST: Employees/Delete/5
        // [HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            var pEntry = _unitOfWork.ProductEntryRepo.Get(id);
            _unitOfWork.ProductEntryRepo.Delete(pEntry);
            _unitOfWork.save();
            return RedirectToAction(nameof(Index));
        }


        //public IActionResult Search(string value)
        //{
        //    var deps = string.IsNullOrEmpty(value) ? _unitOfWork.ProductEntryRepo.GetAll()
        //        : _unitOfWork.ProductEntryRepo.GetAll()
        //        .Where(e => e.FirstName.ToLower().Contains(value.ToLower()) || e.LastName.ToLower().Contains(value.ToLower()));
        //    return Json(new
        //    {
        //        success = true,
        //        message = "All Data is back",
        //        data = deps
        //    });
        //}


        //public IActionResult GetModal(int id)
        //{
        //    return PartialView("_Modal",
        //        _unitOfWork.ProductEntryRepo.Get(id)
        //        );
        //}
    }
}


/*
 edit
search
 
 */

Web/Views/ProductEntry/Create.cshtml
@model DatabaseContext.Models.ProductEntry
@if(TempData["SweetAlertPE"] != null)
        {

    <div id="swalme2"></div>
    TempData["SweetAlertPE"] = null;
}
<form  method="post" action="@Url.Action("Create","ProductEntry")">
    <div class="form-group">
    <label asp-for = "SupplierId"> Supplier </label>
    <select class="btn slc btn-lg dropdown-toggle dropdown-menu-right" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" asp-for="SupplierId" asp-items="@ViewBag.suppliers">
    @*<select data-live-search="true" asp-for="SupplierId" asp-items="@ViewBag.suppliers">*@
    </select>
    <label asp-for="Date"></label>
    <input autocomplete="off" asp-for="Date" class="form-control" />
    </div>
    <input class="btn btn-sub " type="submit" />
</form>
      <script>
           //var els = document.getElementById("swalme");
           var els2 = document.getElementById("swalme2");
           if (els2!=null){
                    Swal.fire({
                      icon: 'error',
                      title: 'Oops...',
                      text: 'Invalid Information!',
                      showCancelButton: false,
                      showConfirmButton: false,
                      timer:3000
                    })
           }
    </script>

Web/Views/ProductEntry/Delete.cshtml
@model DatabaseContext.Models.ProductEntry

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete the Entry with following information ?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
    </dl>
    <br />
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Web/Views/ProductEntry/Edit.cshtml
@model DatabaseContext.Models.ProductEntry

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>
<hr />
<div>
    <div>
        <form asp-action="Edit">
            <label asp-for = "SupplierId"> Supplier </label>
            <select class="btn btn-secondary btn-lg dropdown-toggle dropdown-menu-right" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" asp-for="SupplierId" asp-items="@ViewBag.suppliers">
            </select>
            <div class="pe-date">
            <label asp-for="Date"></label>
            <input autocomplete="off" asp-for="Date" class="form-control" />
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Save" onclick="savechanges()" class="btn btn-sub" />
            </div>
        </form>
    </div>
</div>

<div>
       <a class="back" asp-action="Index"> &lt Back to List</a>
</div>

Web/Views/ProductEntry/Index.cshtml
@model List<DatabaseContext.Models.ProductEntry>
@*
@{ 
    ViewData["title"] = "Index";
}*@

@if(TempData["SweetAlertProduct"] != null)
        {

    <div id="swalme"></div>
    TempData["SweetAlertPE"] = null;
}
<div id="msg" class="row my-2">
    <p>
        @TempData["Message"]
    </p>
</div>
<div class="row my-3">
    <div class="col-4">
        <a class="btn btn-primary" href="@Url.Action("Create","ProductEntry")">Create PEntry</a>
    </div>
@*    <div class="col-4">
        <input type="text" class="form-control srch text-success" placeholder="Search..." onkeyup="search(this.value)" />
    </div>*@
</div>
@*<div class="row my-3">
    <select onchange="alert(this.value)" class="form-control" asp-items="@ViewBag.suppliers"></select>
</div>*@
<div id ="btnshow" style = " display : none">
<table class="table table-bordered">
    <thead>
        <tr>
            @*<th>Id</th>*@
            <th>supplier</th>
            <th>Date</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
             <tr>
                @*<td>@item.Id</td>*@
                <td>@(item.Supplier?.Name ?? "error")</td>
                <td>@item.Date</td>
                <td>
                <a asp-action="Edit" asp-route-id="@item.Id" class="btn  btn-warn">Edit</a>
                <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>
</div>

<button class="btn btn-warn" onclick="showButton()">Get ALL Entries</button>

<div id="modal-container">

</div>
@section Scripts {
    <script>
        function get() {
            let i = 10;
            let string = `${i}`;
            $.ajax({
                url: '@Url.Action("GetCustomers", "Customer")',
                type: 'GET',
                dataType: 'json',
                beforeSend: function() {
                    let timerInterval
                    Swal.fire({
                      title: 'Loading...',
                      //html: 'I will close in <b></b> milliseconds.',
                      timer: 1000,
                      timerProgressBar: true,
                      didOpen: () => {
                        Swal.showLoading()
                        const b = Swal.getHtmlContainer().querySelector('b')
                        timerInterval = setInterval(() => {
                          b.textContent = Swal.getTimerLeft()
                        }, 100)
                      },
                      willClose: () => {
                        clearInterval(timerInterval)
                      }
                    }).then((result) => {
                      if (result.dismiss === Swal.DismissReason.timer) {
                        console.log('I was closed by the timer')
                      }
                    });
                },
                success: function(response) {
                    if (response.success) {
                        $.each(response.data, (index, item) => {
                            $('tbody').append(` <tr>
                                                    <td>${item.id}</td>
                                                    <td>${item.date}</td>
                                                    <td>${item.supplier.name}</td>
                                                    <td>
                                                        <button class="btn btn-warning" onclick="showModal('${item.id}')">Edit</button>
                                                        <button class="btn btn-danger">Delete</button>
                                                    </td>
                                                </tr>`)
                        })
                    }
                    else {
                        alert(response.message)
                    }
                },
                error: function(msg) {
                    console.error(msg);
                }
            })
        }
    </script>
    <script>
        function search(val) {
            $.ajax({
                url: '@Url.Action("Search", "Customer")' + '?value=' + val,
                type: 'GET',
                dataType: 'json',
                beforeSend: function() {
                    $('tbody').html('')
                },
                success: function(response) {
                    if (response.success) {
                        $.each(response.data, (index, item) => {
                            $('tbody').append(` <tr>
                                                    <td>${item.id}</td>
                                                    <td>${item.name}</td>
                                                    <td>
                                                        <button class="btn btn-warning" onclick="showModal('${item.id}')">Edit</button>
                                                        <button class="btn btn-danger">Delete</button>
                                                    </td>
                                                </tr>`)
                        })
                    }
                    else {
                        alert(response.message)
                    }
                },
                error: function(msg) {
                    console.error(msg);
                }
            })
        }
    </script>
    <script>
        function showModal(id) {
            alert(id);
            $.ajax({
                url: '@Url.Action("GetModal", "Customer")' + "?id=" + parseInt(id),
                type: 'GET',
                dataType: 'html',
                success: function(response) {
                    $('#modal-container').html(response); 
                    $('.modal').modal('show');
                    $.validator.unobtrusive.parse('form-id');
                },
                error: function(msg) {
                    console.error(msg);
                }
            })
        }
    </script>
    <script>
        function showButton(){
           var el = document.getElementById("btnshow");
           el.style.display = "table";
        }
    </script>
   <script>
           var els = document.getElementById("swalme");
           //var els2 = document.getElementById("swalme2");
           if (els!=null){
           Swal.fire({
                      icon: 'success',
                      title: 'Saved',
                      showCancelButton: false,
                      showConfirmButton: false,
                      timer:3000
                    })
           }
           //else if(els2 != null){
           // Swal.fire('OOOOOOPS succefully');
           //}
    </script>
}   

Web/Views/ProductEntry/_Modal.cshtml
@*@model DatabaseContext.Models.Customer
<div class="modal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header"></div>
            <form asp-action="Edit" asp-controller="Customer">
                <div class="modal-body">
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name"></span>
                </div>
            <div class="modal-footer">
                <input type="submit" class="btn btn-primary" value="Submit" />
                <button class="btn btn-light" data-dismiss="modal">Cancel</button>
            </div>
            </form>
        </div>
    </div>
</div>*@